import { PageHistorial } from "@/app/components";
import { Metadata } from "next";
export const metadata: Metadata = {
    title: "HISTORIAL",
    description: "Generated by create next app",
  };
export default function Page() {
  return (
    <PageHistorial/>
  );
}

