
import { PageConsultas } from "@/app/components";
// import axios from "axios";
// import { useEffect } from "react";
import { Metadata } from "next";
export const metadata: Metadata = {
    title: "CONSULTAS",
    description: "Generated by create next app",
  };


export default function Page() {
    // useEffect(() => {
    //     const getPerfil = async () => {
    //       const response = await axios.get("/api/roles");
    //       // si el rol no es de edu manda a per
    //       if (response.data.usuario.rol !== "estudiante") {
    //         window.location.pathname = "/per";
    //       }
    //     };
    //     getPerfil();
    //   }, []);
    return (
        <PageConsultas/>
    );
}