

import { PageConsultasPendientes } from "@/app/components";
import { Metadata } from "next";
export const metadata: Metadata = {
    title: "CONSULTAS | PENDIENTES",
    description: "Generated by create next app",
  };

export default function Page() {
  return(
    <>
      <PageConsultasPendientes/>
    </>
  )
}
