
import { PageProgramados } from "@/app/components";
import { Metadata } from "next";
export const metadata: Metadata = {
    title: "PROGRAMADAS",
    description: "Generated by create next app",
  };

export default function Page() {
    return (
      <>
        <PageProgramados/>
      </>  
      
    )
}