

import { PagePreguntas } from "@/app/components";
import { Metadata } from "next";
export const metadata: Metadata = {
    title: "PREGUNTAS",
    description: "Generated by create next app",
  };
export default function Page() {
        return (
          <>
          <PagePreguntas/>
          </>
        )
      }
      