/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/ban-ts-comment */

import { PageCitasProgramadas } from '@/app/components'
import { Metadata } from "next";
export const metadata: Metadata = {
    title: "CITAS | PROGRAMADAS",
    description: "Generated by create next app",
  };


export default function Page() {
  return(
    <>
    <PageCitasProgramadas/>
    </>
  )
}
