


import { PageSoporte } from "@/app/components";
import { Metadata } from "next";
export const metadata: Metadata = {
    title: "SOPORTE",
    description: "Generated by create next app",
  };
export default function Page() {
        return (
          <>
          <PageSoporte/>
          </>
        )
      }
      
